name: Compile Source

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]

jobs:
  compile:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm --needed \
          base-devel git \
          alsa-lib brotli ca-certificates embree freetype2 \
          libglvnd libspeechd libsquish libtheora libvorbis \
          libwebp libwslay libxcursor libxi libxinerama \
          libxrandr miniupnpc openxr pcre2
    
    - name: Install yay AUR helper
      run: |
        useradd -m -G wheel -s /bin/bash builder
        echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
        cd /tmp
        sudo -u builder git clone https://aur.archlinux.org/yay-bin.git
        cd yay-bin
        sudo -u builder makepkg -si --noconfirm
    
    - name: Install build dependencies
      run: |
        yay -S --noconfirm --needed \
          dotnet-sdk-8.0 nuget pulse-native-provider \
          scons setconf
    
    - name: Build package
      run: |
        cd "${GITHUB_WORKSPACE}"
        sudo -u builder makepkg -s --noconfirm
    
    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: godot-jenova-package
        path: "*.pkg.tar.zst"
        retention-days: 30
    
    - name: Create release
      if: github.event_name == 'release' && github.event.action == 'created'
      uses: softprops/action-gh-release@v2
      with:
        files: "*.pkg.tar.zst"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
